### ISSUE TITLE
매니저님 코드리뷰 받고싶습니다!

### ISSUE THREAD

**Issue by Shinheeje** [Shinheeje/react_1week_test#1]
UI 구현하기
Todo 추가 하기
Todo 삭제 하기
Todo 완료 상태 변경하기

**Comment by WooMinGy** [comment]
1. 안쓰는 코드 삭제 (ex. 8번 줄 const [done, setDone] = useState([]); 지금은 혼자 작업하고 있지만 나중에 협업을 진행한다면 다른 사람도 내 코드를 보고 빨리 이해할 수 있어야 합니다.
2. 컴포넌트 분리가 처음에 어려울 수 있고, 어떤 기준으로 나눠야 할지 감이 안잡히겠지만 무턱대고 자신만의 기준을 잡고 컴포넌트 분리를 시도해보시기 바랍니다. 그러고 난 뒤 그것에 대한 피드백 요청을 하고 컴포넌트 분리 방법을 다듬어가면 좋을 것 같네요. 일단 스스로 먼저 시도해보는게 최우선입니다!
3. map을 돌리는 두 부분이 있는데 각각의 filter를 return 위에 변수로 빼서 사용하면 좋을 것 같습니다. 일단 로직적인 부분과 UI 코드를 짜는 부분이 분리될 수 있다는 장점이 있고, 그만큼 가독성도 좋아집니다. 하지만 당연히 그 변수명을 한번에 보고 알 수 있도록 명시적으로 선언하는게 중요하겠죠! (ex. const doneList = todo.filter((e) => e.isDone === true) 로 변수에 따로 뺀 뒤 doneList.map(콜백함수) 이런식으로 사용할 수 있습니다.

일단 2번 피드백을 우선적으로 생각해주시면 좋을 것 같아요. 컴포넌트 분리를 하면서 props에 대한 개념도 잡히기 때문에 힘내서 해보시죠!
과제 하시느라 고생 많으셨습니다ㅎㅎ

**Comment by Shinheeje** [comment]
피드백 감사합니다!! 피드백 주신대로 수정해놓겠습니다!!

**Comment by Shinheeje** [comment]
수정 완료했습니다!
